// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace OnlineProdavnica.Migrations
{
    [DbContext(typeof(OnlineProdavnicaContext))]
    partial class OnlineProdavnicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Artikal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RadnjaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RadnjaID");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("Models.KorpaSpoj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArtikalID")
                        .HasColumnType("int");

                    b.Property<int?>("RadnjaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ArtikalID");

                    b.HasIndex("RadnjaID");

                    b.ToTable("KorpaSpojevi");
                });

            modelBuilder.Entity("Models.Racun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Iznos")
                        .HasColumnType("int");

                    b.Property<int?>("RadnjaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RadnjaID");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("Models.RacunSpoj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArtikalID")
                        .HasColumnType("int");

                    b.Property<int?>("RacunID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ArtikalID");

                    b.HasIndex("RacunID");

                    b.ToTable("RacunSpojevi");
                });

            modelBuilder.Entity("Models.Radnja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Radnje");
                });

            modelBuilder.Entity("Models.Artikal", b =>
                {
                    b.HasOne("Models.Radnja", "Radnja")
                        .WithMany("Artikli")
                        .HasForeignKey("RadnjaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radnja");
                });

            modelBuilder.Entity("Models.KorpaSpoj", b =>
                {
                    b.HasOne("Models.Artikal", "Artikal")
                        .WithMany("ArtikliKorpa")
                        .HasForeignKey("ArtikalID");

                    b.HasOne("Models.Radnja", "Radnja")
                        .WithMany()
                        .HasForeignKey("RadnjaID");

                    b.Navigation("Artikal");

                    b.Navigation("Radnja");
                });

            modelBuilder.Entity("Models.Racun", b =>
                {
                    b.HasOne("Models.Radnja", "Radnja")
                        .WithMany()
                        .HasForeignKey("RadnjaID");

                    b.Navigation("Radnja");
                });

            modelBuilder.Entity("Models.RacunSpoj", b =>
                {
                    b.HasOne("Models.Artikal", "Artikal")
                        .WithMany("ArtikliRacun")
                        .HasForeignKey("ArtikalID");

                    b.HasOne("Models.Racun", "Racun")
                        .WithMany("RacunArtikli")
                        .HasForeignKey("RacunID");

                    b.Navigation("Artikal");

                    b.Navigation("Racun");
                });

            modelBuilder.Entity("Models.Artikal", b =>
                {
                    b.Navigation("ArtikliKorpa");

                    b.Navigation("ArtikliRacun");
                });

            modelBuilder.Entity("Models.Racun", b =>
                {
                    b.Navigation("RacunArtikli");
                });

            modelBuilder.Entity("Models.Radnja", b =>
                {
                    b.Navigation("Artikli");
                });
#pragma warning restore 612, 618
        }
    }
}
